"use client";

import { Download, Share2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import type { ReportMeta } from "@/lib/mock/report-data";

export function ReportFooter({ meta }: { meta: ReportMeta }) {
  return (
    <footer className="border-t border-zinc-800/80 bg-[#09090b]/80">
      <div className="mx-auto flex max-w-[1400px] flex-col gap-4 px-4 py-6 sm:flex-row sm:items-center sm:justify-between sm:px-6">
        <div className="flex items-center gap-2 text-[11px] text-zinc-500">
          <div className="grid size-6 place-content-center rounded bg-cyan-500 text-[10px] font-bold text-cyan-950">C</div>
          <span>Generated by ComplytAI v4.2 — AI Compliance Intelligence Platform</span>
        </div>
        <p className="text-center text-[11px] text-zinc-600 sm:flex-1">
          Report ID: {meta.reportId} | Generated {meta.generatedAt} | Corpus: {meta.corpusVersion} |{" "}
          <strong className="font-semibold text-zinc-500">Confidential</strong>
        </p>
        <div className="flex justify-end gap-2">
          <Button variant="outline" size="sm" className="border-zinc-700/80 text-zinc-400">
            <Share2 className="size-3.5" />
            Share
          </Button>
          <Button size="sm" className="bg-cyan-600 text-cyan-950 hover:bg-cyan-500">
            <Download className="size-3.5" />
            Export PDF
          </Button>
        </div>
      </div>
    </footer>
  );
}
